[package]
name = "spacesim_simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_utility_ai = { path = "../bevy_utility_ai" }
bevy = { version = "0.10.1", default-features = false }
strum = "0.24.1"
strum_macros = "0.24.3"

