[package]
name = "bevy_utility_ai"
version = "0.0.1"
edition = "2021"

[dependencies]
bevy_utility_ai_macros = { path = "../bevy_utility_ai_macros" }
bevy = { version = "0.10", default-features = false }

[dev-dependencies]
trybuild = "1"