[package]
name = "spacesim"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_utility_ai = { path = "../bevy_utility_ai" }
spacesim_simulation = { path = "../spacesim_simulation" }
bevy = "0.10"
bevy_egui = "0.20"
egui_extras = "0.21"
strum = "0.24"
strum_macros = "0.24"
