[package]
name = "bevy_utility_ai_macros"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bevy = "0.10"
syn = { version = "1", features = ["extra-traits", "full", "fold"] }
quote = "1"
proc-macro2 = "1"
proc-macro-error = "1"
